FROM python:3.8.10

COPY . /app

RUN apt update
RUN apt install libgraphviz-dev graphviz -y

RUN curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
RUN bash Mambaforge-$(uname)-$(uname -m).sh -b

RUN ~/mambaforge/bin/mamba install pytorch cudatoolkit=10.2 tensorflow tensorflow-hub -c pytorch -y

RUN pip install https://github.com/deepset-ai/haystack/archive/refs/tags/v0.10.0.zip
RUN pip install spacy

WORKDIR /app
RUN pip install -r requirements.txt

RUN python -m spacy download en_core_web_sm
RUN python -m spacy download en_core_web_trf

# define the default command to run when starting the container
CMD ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "--workers", "1", "app.main:app"]