version: '3'

services:

  python:
    # container_name: ml-api-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "4000:4000"
      command: ["poetry", "run", "uvicorn", "app.main:app", "--host=0.0.0.0", "--port=4000", "--workers=10"]

  unit-tests:
    image: fastapi-ml-scaffolding-unittests
    build:
      dockerfile: tests/Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - DEFAULT_MODEL_PATH=/sample_model/lin_reg_california_housing_model.joblib
    volumes:
      - .:/app

