vesion: '1.0'

# Add conf yml filenames here to bootstrap those processes

services:    # define all the building-blocks for Pipeline
  - search
  - embedding
  - ner
  - qa
  - question-classifier
  - question-generation
  - similarity
  - spacy
  - summarizer
  - zeroshot-classifier
  # - preprocessor
  #
logfile: /tmp/nlpservice.log
loglevel: 20
