vesion: '0.7'

# Add conf yml filenames here to bootstrap those processes

services:    # define all the building-blocks for Pipeline
  - qa
  # - spacy
  # - embedding
  # - ner
  # - similarity
  # - zeroshot-classifier
  # - question-classifier
  # - question-generation
  # - summarizer
  # - preprocessor
