package: app.api.preprocess

components:
  - name: Preprocessor
    type: PreProcessor
    params:
      split_by: word
      split_length: 1000

pipelines:
  - name: preprocess
    type: Indexing
    nodes:
      - name: Preprocessor
        inputs: [File]

