version: '1.0'

title: Question classifier
description: |
  TBD

package: app.api.question
tags:
  - classifier

components:    # define all the building-blocks for Pipeline
  - name: CategoryQuestion
    type: Category
    params:
      category: "question/statement"
  - name: CategoryStatement
    type: Category
    params:
      category: "keyword"
  - name: QueryClassifier
    type: TransformersQueryClassifier
    params:
      model_name_or_path: shahrukhx01/bert-mini-finetune-question-detection

pipelines:
  - name: question    # classify queries in question/statement classes
    type: Query
    nodes:
      - name: QueryClassifier
        inputs: [Query]
      - name: CategoryQuestion
        inputs: [QueryClassifier.output_1]
      - name: CategoryStatement
        inputs: [QueryClassifier.output_2]
