# export QA_FACETEDDOCUMENTSTORE_PARAMS_HOST=10.120.10.204
# export QA_FACETEDDOCUMENTSTORE_PARAMS_PORT=60168
# export QA_FACETEDDOCUMENTSTORE_PARAMS_INDEX=data_searchui
# export QA_FACETEDDOCUMENTSTORE_PARAMS_EMBEDDING_FIELD=nlp_500.embedding
#
# export SEARCH_FACETEDDOCUMENTSTORE_PARAMS_HOST=10.120.10.204
# export SEARCH_FACETEDDOCUMENTSTORE_PARAMS_PORT=60168
# export SEARCH_FACETEDDOCUMENTSTORE_PARAMS_INDEX=data_searchui
# export SEARCH_FACETEDDOCUMENTSTORE_PARAMS_EMBEDDING_FIELD=embedding_field
#
# export FEEDBACK_FEEDBACKSTORE_PARAMS_HOST=10.120.10.204
# export FEEDBACK_FEEDBACKSTORE_PARAMS_PORT=60168
# export FEEDBACK_FEEDBACKSTORE_PARAMS_INDEX=data_searchui
# export FEEDBACK_FEEDBACKSTORE_PARAMS_LABEL_INDEX=data_searchui-feedback
# export FEEDBACK_FEEDBACKSTORE_PARAMS_CREATE_INDEX=True

export SEARCH_SERVICES=qa,search,similarity,qasearch,embedding
